#!/bin/zsh

## Unified log entries can be retrieved with: 
##    log show --predicate 'eventMessage contains "Reactivated BT"' --info --debug
##    log show --predicate 'eventMessage contains "Killed Safari for"' --info --debug
##
##  Usage: sudo ./btenforce -configure
##         sudo ./btenforce -debug
##         sudo ./btenforce # No arguments for normal operation.
##
##  Change Log:
##   4/2/2026 - Added -debug option to show the contents of the configuration file.
##            - Added configuration mode to make it easy to configure/reconfigure. 
##            - Added full time options instead of hour only.
##            - Renamed the application to btenforce (lowercase).
##   4/6/2026 - Added time constraint override option.
##            - Added ability to run as a daemon.
##  5/15/2026 - Version 2.1: 
##            - Reduced the daemon interval to 5 seconds.
##            - Abandoned the app bundle structure. The package installer places
##              the main script in /usr/local/bin/btenforce and blueutil in 
##              /usr/local/share/btenforce/blueutil, and the daemon in 
##              /Library/LaunchDaemons/com.itech.btenforce.plist.
##            - btenforce is now a combination of the Bluetooth utility plus
##              other functions such as Safari control and login item control. 
##              See the config file for more information.
##            - The included version of blueutil is version 9 due to some irregularities 
##              with newer versions on macOS 26.
##            - Removed ANSI color coding from log messages.
##            - Added logging to configuration function.
##            - Added comment indicating that the script is running as a standard user.
##            - Prevents reconfiguring by standard users.
##            - Cleaned up redundant login check.
##            - Added log retention period to the configuration options.
##            - Added function to append missing configuration variables to the config file.
##            - Added comprehensive configuration variable validation in post-install script.
##            - Corrected the installation function to check for the source files before copying them.
##            - Replaced deprecated launchctl unload/bootstrap with bootout/bootstrap.
##            - Added version to blueutil on install/update for logging.
##            - Added check for blueutil and then copy it from /usr/local/share/btenforce/blueutil if not found in /usr/local/bin.
##            - Added MDM_TYPE variable for clarity in config file.
##            - Added version to the log header in the config file for easy identification.
##            - Refined configuration function for usability and convenience. It will
##              now check for configuration errors in the config file and report
##              them to the user.
##            - Added parameters to postinstall script for Jamf Pro MDM and 
##              Mosyle MDM. See the notes in the postinstall script for more
##              information.
##            - Enhanced time entry and validation for the configuration 
##              function.
##            - Added warning when configuring Safari function with osascript
##              method on macOS.
##            - Added the method used to configure btenforce to the config file along with the time and date of the configuration.
##            - Reduced unessential noise from logs.
##            - Added check for BTENFORCE_ACTIVE in config file and exit if not found.
##            - Added i-Tech banner with support info.
##            - Changed logic to continue if no user is logged on, then skip the controls and log the exit code.
##            - Added trap for INT and TERM signals to log the exit code and exit.
##            - Added trap for ERR signal to log the error message and exit.
##            - Reduced unessential noise from logs when school is not in session by adding a flag file to
##              prevent the script from logging on every execution.
##            - Modified the shebang from /bin/zsh to /bin/bash for compatibility in the post-install script.
##              since that will be most likely executed by an MDM and if Mosyle, must be Bash.
##
## Author: Keith Myers | keith.myers@i-techsupport.com
##
## Since this script is called repeatedly, the config file formatting is extremely
## strict to prevent errors. Each variable is on its own line and is in the format
## VARIABLE="value".
## 
## This script is designed to be called by a daemon.
## It must be ran as root.
##
## macOS 26 and higher: Due to Apple's constraints on managing Bluetooth,
## when the utility first attempts to enable Bluetooth, a prompt is displayed
## to the user asking for permission to allow Bluetooth control. This prompt
## must be answered with 'Allow' before the utility can be effective. 
##
## LICENSE
## Copyright 2026, i-Tech Support Inc.
## https://i-techsupport.com | info@i-techsupport.com | (407) 265-2000
##
## Permission is hereby granted, free of charge, to any person obtaining a copy of 
## this software and associated documentation files (the Software), to deal in 
## the Software without restriction, including without limitation the rights to use, 
## copy, modify, or merge, the Software, and to permit persons to whom the Software is
## furnished to do so, subject to the following conditions:
##
## The above copyright notice, URL, email address, and this permission notice shall be 
## included in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
## INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
## PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
## FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR 
## OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
## DEALINGS IN THE SOFTWARE.

## ═══════════════════════════════════════════════════════════════════════════════════════ ##

VERSION="2.1"
SCRIPT_PATH="${0:A}"
EXIT_CODE="0"
ACTIVE_USER="false"
NW_FLAG="/Library/Application Support/i-Tech/btenforce.nw"
REPO="https://github.com/i-TechSupport-orlando/btenforce"

# Application configuration file.
BTENFORCE_CONFIG="/Library/Application Support/i-Tech/btenforce.env"
BTENFORCE_LOG_FILE="/var/log/btenforce.log"
TODAY=$( date +%Y-%m-%d )

PLIST="/Library/LaunchDaemons/com.itech.btenforce.plist"

# Username of the user currently logged on and their ID.
loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )
if [[ -z "$loggedInUser" ]]; then
	# Exit if no user is logged in. btenforce is user-facing.
	append_log "No user logged in."
	EXIT_CODE=1
else
	ACTIVE_USER="true"
fi

# Get the user ID of the logged-in user.
uid=$( id -u "${loggedInUser}" )

# If no user ID is found for the logged in user, log and change exit code.
if [[ -z "$uid" ]]; then
	append_log "No user ID found for user ${loggedInUser}. Exiting."
	EXIT_CODE=1
fi

# Add the date and time stamp to the log file.
append_log () {
    local message="$1"
    
    # Strip ANSI color codes AND leading newlines for the log files.
    # The sed pipeline removes ANSI escape sequences and deletes the first line if it is empty.
    local clean_text="$( echo -e "$message" | sed 's/\x1b\[[0-9;]*m//g' | sed '1{/^$/d;}' )"
    
    local date_stamp="$( date +"%Y-%m-%d %H:%M:%S" )"
    local file_log_msg="${date_stamp} -- ${clean_text}"
    local syslog_msg="version ${VERSION} -- ${clean_text}"

    # If stdout is a terminal (interactive session), keep the colors.
    if [[ -t 1 ]]; then
        # Echo the message with the ANSI color codes to the terminal.
        echo -e "$message"
    fi

    # Append clean message to the persistent log file
    echo "$file_log_msg" >> "$BTENFORCE_LOG_FILE"
    
    # Log to syslog without echoing to stderr again
    logger -i -t btenforce "$syslog_msg"
}

# Function to display debug information.
debug_info() {
    append_log "BTENFORCE_CONFIG:         ${BTENFORCE_CONFIG}"
    append_log "BTENFORCE_LOG_FILE:       ${BTENFORCE_LOG_FILE}"
    append_log "BTENFORCE_ACTIVE:         ${BTENFORCE_ACTIVE}"
    append_log "TODAY:                    ${TODAY}"
    append_log "APP_BUNDLE_DIR:           ${APP_BUNDLE_DIR}"
    append_log "PLIST:                    ${PLIST}"
    append_log "BLUEUTIL_ALLOW_ROOT:      ${BLUEUTIL_ALLOW_ROOT}"
    append_log "SAFARI_CONTROL:           ${SAFARI_CONTROL}"
    append_log "SAFARI_CONTROL_METHOD:    ${SAFARI_CONTROL_METHOD}"
    append_log "loggedInUser:             ${loggedInUser}"
    append_log "User ID:                  ${uid}"
    append_log "TIME_CONSTRAINT_OVERRIDE: ${TIME_CONSTRAINT_OVERRIDE}"
}

# Function to validate that a time value is formatted correctly. 24-hour clock.
check_time_integer() {
    local time="$1"
    local time_regex='^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$'

    if [[ ! "$time" =~ $time_regex ]]; then
        return 1
	fi

	# Split the string on the colon character into an array.
	local time_array=(${(s/:/)time})

	local hour="${time_array[1]}"
	local minute="${time_array[2]}"

	# Using 10# forces base-10 evaluation, avoiding octal errors with 08 or 09.
	if (( 10#$hour >= 0 && 10#$hour <= 23 )) && (( 10#$minute >= 0 && 10#$minute <= 59 )); then
		return 0
	fi
    return 1
}

add_leading_zero() {
    local time="$1"
	local time_array=(${(s/:/)time})
	local hour="${time_array[1]}"
	local minute="${time_array[2]}"

	# Strip any existing leading zeros to avoid double padding
	hour="${hour#"${hour%%[!0]*}"}"
	minute="${minute#"${minute%%[!0]*}"}"
	
	# If they were entirely zeros (e.g. "00"), they become empty. Default to 0.
	hour="${hour:-0}"
	minute="${minute:-0}"

	printf "%02d:%02d\n" "$hour" "$minute"
}


# Configuration function. Called with -configure argument.
configure_btenforce() {
    failed_items=0
    YELLOW=$'\033[1;33m'
    GREEN=$'\033[0;32m'
    BLUE=$'\033[1;34m'
    RED=$'\033[0;31m'
    ORANGE=$'\033[38;2;255;165;0m'
    NC=$'\033[0m' # No color

    clear
    local total_options=10
    local option_number=0

    TERM=xterm-256color

    echo -e " ╔═════════════════════════════╗ "
    echo -e " ║   btenforce Config Builder  ║ "
    echo -e " ║ ${ORANGE} _     _____         _      ${NC}║ "
    echo -e " ║ ${ORANGE}(_)   |_   _|__  ___| |___  ${NC}║ "
    echo -e " ║ ${ORANGE}| |_____| |/ _ \/ __| '_  \ ${NC}║ "
    echo -e " ║ ${ORANGE}| |_____| |  __/ (__| | | | ${NC}║ "
    echo -e " ║ ${ORANGE}|_|     |_|\___|\___|_| |_| ${NC}║ "
    echo -e " ║                             ║ "
    echo -e " ║ ▶︎ https://i-techsupport.com ║ "
    echo -e " ║ ☎ (407) 265-2000 option: #1 ║ "
    echo -e " ║ ✉ support@i-techsupport.com ║ "
    echo -e " ║ Author: Keith Myers, i-Tech ║ "
    echo -e " ║ (C) 2026 i-Tech Support Inc ║ "
    echo -e " ╚═════════════════════════════╝ "
    echo ""

    if (( EUID != 0 )); then
        append_log "\n${RED}Error: This script must be run with sudo or as root.${NC}\n" >&2
        exit 1
    fi

    echo -e "\nPlease note that this utility changes the configuration of btenforce on"
    echo -e "${ORANGE}this computer only${NC}. To change the config on multiple computers, use the"
    echo -e "post-install script: btenforce-postinstall.sh using an MDM.\n"

    echo -e "Press ENTER for the default value shown in square brackets or make a selection:\n"

    ((option_number++))
    # Enable/disable the daemon as a whole.
    if read -s -k 1 -t 600 "BTENFORCE_ACTIVE?[${option_number}/${total_options}] Enable btenforce? ([${ORANGE}Y${NC}]/N): "; then
        if [[ "$BTENFORCE_ACTIVE" == "Y" || "$BTENFORCE_ACTIVE" == "y" ]]; then
            BTENFORCE_ACTIVE="true"
            append_log "\n${GREEN}You indicated yes. btenforce is now enabled.${NC}"
        elif [[ "$BTENFORCE_ACTIVE" == "N" || "$BTENFORCE_ACTIVE" == "n" ]]; then
            BTENFORCE_ACTIVE="false"
            append_log "\n${RED}You indicated no. btenforce is now disabled.${NC}"
        else
            append_log "\n${GREEN}Invalid entry. Defaulting to enable. btenforce is now enabled.${NC}"
            BTENFORCE_ACTIVE="true"
        fi
    else
        append_log "\n${GREEN}Timeout has expired. Defaulting to enable. btenforce is now enabled.${NC}"
        BTENFORCE_ACTIVE="true"
    fi

    echo "-------------------------------"
    ((option_number++))
    # Safari option. 'enforce' or 'allow'
    if read -s -k 1 -t 600 "SAFARI_CONTROL?[${option_number}/${total_options}] Enforce Safari restrictions? (force students to use Chrome, for example) (Y/[${ORANGE}N${NC}]): "; then
        if [[ "$SAFARI_CONTROL" == "Y" || "$SAFARI_CONTROL" == "y" ]]; then
            SAFARI_CONTROL="enforce"
            append_log "\n${GREEN}You indicated yes. Safari restrictions are now enabled.${NC}"
        elif [[ "$SAFARI_CONTROL" == "N" || "$SAFARI_CONTROL" == "n" ]]; then
            SAFARI_CONTROL="allow"
            append_log "\n${RED}You indicated no. Safari restrictions are now disabled.${NC}"
        else
            append_log "\n${GREEN}Invalid entry. Defaulting to allow. Safari restrictions are now disabled.${NC}"
            SAFARI_CONTROL="allow"
        fi
    else
        append_log "\n${GREEN}Timeout has expired. Defaulting to allow. Safari restrictions are now disabled.${NC}"
        SAFARI_CONTROL="allow"
    fi

    echo "-------------------------------"

    ((option_number++))
    # Bluetooth option. 'enforce' or 'allow'
    if read -s -k 1 -t 600 "BLUETOOTH_CONTROL?[${option_number}/${total_options}] Enforce Bluetooth restrictions? (students will not be able to turn off Bluetooth) (Y/[${ORANGE}N${NC}]): "; then
        if [[ "$BLUETOOTH_CONTROL" == "Y" || "$BLUETOOTH_CONTROL" == "y" ]]; then
            BLUETOOTH_CONTROL="enforce"
            append_log "\n${GREEN}You indicated yes. Bluetooth enforcement is now enabled.${NC}"
        elif [[ "$BLUETOOTH_CONTROL" == "N" || "$BLUETOOTH_CONTROL" == "n" ]]; then
            BLUETOOTH_CONTROL="allow"
            append_log "\n${RED}You indicated no. Bluetooth enforcement is now disabled.${NC}"
        else
            append_log "\n${GREEN}Invalid entry. Defaulting to allow. Bluetooth enforcement is now disabled.${NC}"
            BLUETOOTH_CONTROL="allow"
        fi
    else
        append_log "\n${GREEN}Timeout has expired. Defaulting to allow. Bluetooth enforcement is now disabled.${NC}"
        BLUETOOTH_CONTROL="allow"
    fi

    echo "-------------------------------"

    ((option_number++))
    # Login item controls. 'enforce' or 'allow'
    if read -s -k 1 -t 600 "LOGIN_ITEM_CONTROL?[${option_number}/${total_options}] Enforce login item controls? (restrict students from adding or removing login items) (Y/[${ORANGE}N${NC}]): "; then
        if [[ "$LOGIN_ITEM_CONTROL" == "Y" || "$LOGIN_ITEM_CONTROL" == "y" ]]; then
            LOGIN_ITEM_CONTROL="enforce"
            append_log "\n${GREEN}You indicated yes. Students will not be able to save login items.${NC}"
        elif [[ "$LOGIN_ITEM_CONTROL" == "N" || "$LOGIN_ITEM_CONTROL" == "n" ]]; then
            LOGIN_ITEM_CONTROL="allow"
            append_log "\n${RED}You indicated no. Students will be able to save login items.${NC}"
        else
            append_log "\n${GREEN}Invalid entry. Defaulting to allow. Students will be able to save login items.${NC}"
            LOGIN_ITEM_CONTROL="allow"
        fi
    else
        append_log "\n${GREEN}Timeout has expired. Defaulting to allow. Students will be able to save login items.${NC}"
        LOGIN_ITEM_CONTROL="allow"
    fi

    echo "-------------------------------"

    ((option_number++))
    # Override time constraints. 'No' means student control enabled on nights/weekends.
    if read -s -k 1 -t 600 "TIME_CONSTRAINT_OVERRIDE?[${option_number}/${total_options}] Override the time constraints and enforce btenforce options 24x7? (Y/[${ORANGE}N${NC}]): "; then
        if [[ "$TIME_CONSTRAINT_OVERRIDE" == "Y" || "$TIME_CONSTRAINT_OVERRIDE" == "y" ]]; then
            TIME_CONSTRAINT_OVERRIDE="true"
            append_log "\n${GREEN}You indicated yes. Time constraint override is enabled. 24x7 enforcement.${NC}"
        elif [[ "$TIME_CONSTRAINT_OVERRIDE" == "N" || "$TIME_CONSTRAINT_OVERRIDE" == "n" ]]; then
            TIME_CONSTRAINT_OVERRIDE="false"
            append_log "\n${GREEN}You indicated no. Time constraint override is disabled. Student control enabled on nights and weekends.${NC}"
        else
            append_log "\n${GREEN}Invalid entry. Defaulting to allow. Time constraint override is disabled.${NC}"
            TIME_CONSTRAINT_OVERRIDE="false"
        fi
    else
        append_log "\n${GREEN}Timeout has expired. Defaulting to allow. Time constraint override is disabled.${NC}"
        TIME_CONSTRAINT_OVERRIDE="false"
    fi

    echo "-------------------------------"

    # ((option_number++))
    # Organization's fully qualified domain name (FQDN).
    # Not used in this version, but will be in a future version.
    # fqdn_regex='^([a-zA-Z0-9-]{1,63}\.)+[a-zA-Z]{2,}$'
    # if read -t 600 "BTENFORCE_DOMAIN?[${option_number}/${total_options}] Enter your organization's fully qualified domain name ([${ORANGE}ENTER${NC}] to skip): "; then
    #     if [[ -z $BTENFORCE_DOMAIN ]]; then
    #         BTENFORCE_DOMAIN=""
    #         append_log "${YELLOW}Skipping FQDN entry.${NC}"
    #     elif [[ $BTENFORCE_DOMAIN =~ $fqdn_regex ]]; then
    #         if [[ "$BTENFORCE_DOMAIN" == *"yourdomain"* ]]; then
    #             append_log "${GREEN}Using default FQDN of ${BTENFORCE_DOMAIN}.${NC}"
    #         else
    #             append_log "${GREEN}Using FQDN of ${BTENFORCE_DOMAIN}.${NC}"
    #         fi
    #     else
    #         append_log "${YELLOW}Invalid value entered: ${BTENFORCE_DOMAIN} Skipping FQDN entry.${NC}"
    #         BTENFORCE_DOMAIN=""
    #     fi
    # else
    #     append_log "${GREEN}Skipping FQDN entry.${NC}"
    #     BTENFORCE_DOMAIN=""
    # fi

    # echo "-------------------------------"

    ((option_number++))
    # Safari blocking option. 'osascript', 'pgrep'
    if read -s -k 1 -t 600 "SAFARI_CONTROL_METHOD?[${option_number}/${total_options}] Enter Safari blocking method: (Osascript/[${ORANGE}P${NC}]grep): "; then
        if [[ "$SAFARI_CONTROL_METHOD" == "O" || "$SAFARI_CONTROL_METHOD" == "o" ]]; then
            SAFARI_CONTROL_METHOD="osascript"
            append_log "\n${GREEN}You indicated Osascript. Safari blocking method is osascript.${NC}"
            append_log "\n${ORANGE}osascript may require a configuration profile to set the permissions. Use pgrep method instead if students are prompted for permissions.${NC}"
        elif [[ "$SAFARI_CONTROL_METHOD" == "P" || "$SAFARI_CONTROL_METHOD" == "p" ]]; then
            SAFARI_CONTROL_METHOD="pgrep"
            append_log "\n${GREEN}You indicated pgrep. Safari blocking method is pgrep.${NC}"
        else
            SAFARI_CONTROL_METHOD="pgrep"
            append_log "\n${GREEN}Invalid entry. Defaulting to pgrep Safari blocking method.${NC}"
        fi
    else
        append_log "\n${GREEN}Timeout has expired. Defaulting to pgrep Safari blocking method.${NC}"
        SAFARI_CONTROL_METHOD="pgrep"
    fi

    echo "-------------------------------"

    ((option_number++))
    # School start time in 24-hour clock. Hour only.
    if read -t 600 "BTENFORCE_START_TIME?[${option_number}/${total_options}] Enter school start time (5 characters as in 07:00 or press ENTER for [${ORANGE}07:00${NC}]): "; then
        if [[ -z "$BTENFORCE_START_TIME" ]]; then
            append_log "${GREEN}Using default school start time of 07:00.${NC}"
            BTENFORCE_START_TIME="07:00"
        else

            # Double check that the time is a valid time.
            BTENFORCE_START_TIME=$( add_leading_zero "$BTENFORCE_START_TIME" )
            if check_time_integer "$BTENFORCE_START_TIME"; then
                append_log "${GREEN}School start time is set to ${BTENFORCE_START_TIME}.${NC}"
            else
                append_log "${RED}Invalid value entered: ${BTENFORCE_START_TIME} - Defaulting to 07:00.${NC}"
                BTENFORCE_START_TIME="07:00"
            fi
        fi
    else
        append_log "${GREEN}Timeout has expired. Defaulting to 07:00.${NC}"
        BTENFORCE_START_TIME="07:00"
    fi

    echo "-------------------------------"  

    ((option_number++))
    # School stop time in 24-hour clock. Hour only.
    if read -t 600 "BTENFORCE_STOP_TIME?[${option_number}/${total_options}] Enter school stop time (5 characters as in 15:00 or press ENTER for [${ORANGE}15:00${NC}]): "; then
        if [[ -z "$BTENFORCE_STOP_TIME" ]]; then
            append_log "${GREEN}Using default school stop time of 15:00.${NC}"
            BTENFORCE_STOP_TIME="15:00"
        else
            # Double check that the time is a valid time.
            BTENFORCE_STOP_TIME=$( add_leading_zero "$BTENFORCE_STOP_TIME" )
            if check_time_integer "$BTENFORCE_STOP_TIME"; then
                append_log "${GREEN}School stop time is set to ${BTENFORCE_STOP_TIME}.${NC}"
            else
                append_log "${RED}Invalid value entered: ${BTENFORCE_STOP_TIME} - Defaulting to 15:00.${NC}"
                BTENFORCE_STOP_TIME="15:00"
            fi
        fi
    else
        append_log "${GREEN}Timeout has expired. Defaulting to 15:00.${NC}"
        BTENFORCE_STOP_TIME="15:00"
    fi

    echo "-------------------------------"

    ((option_number++))
    # Set the retention period for log files. Default is 180 days.
    if read -t 600 "LOG_RETENTION?[${option_number}/${total_options}] Enter log retention period in days from 7-1095 (Press enter for [${ORANGE}180${NC}]): "; then
        if [[ -z "$LOG_RETENTION" ]]; then
            append_log "${GREEN}Using default log retention of 180 days.${NC}"
            LOG_RETENTION="180"
        elif [[ "$LOG_RETENTION" =~ ^(7|8|9|[1-9][0-9]|[1-9][0-9]{2}|10[0-8][0-9]|109[0-5])$ ]]; then
            append_log "${GREEN}Log retention is set to ${LOG_RETENTION} days.${NC}"
        else
            append_log "${RED}Invalid value entered: ${LOG_RETENTION} - Defaulting to 180 days.${NC}"
            LOG_RETENTION="180"
        fi
    else
        append_log "${GREEN}Timeout has expired. Defaulting to 180.${NC}"
        LOG_RETENTION="180"
    fi

    echo "-------------------------------"

    ((option_number++))
    # Log file path. Use a new variable so that the log currently running isn't affected.
    local new_log_path=""
    if read -t 600 "new_log_path?[${option_number}/${total_options}] Enter log file path (press enter for [${ORANGE}${BTENFORCE_LOG_FILE}${NC}]): "; then
        if [[ -z "$new_log_path" ]]; then
            append_log "${GREEN}Using ${BTENFORCE_LOG_FILE}${NC}"
            new_log_path="$BTENFORCE_LOG_FILE"
        else
            append_log "${GREEN}Log file path is set to ${new_log_path}.${NC}"
        fi
    else
        append_log "${GREEN}Timeout has expired. Defaulting to ${BTENFORCE_LOG_FILE}.${NC}"
        new_log_path="$BTENFORCE_LOG_FILE"
    fi

    echo "-------------------------------"


    # Check whether the log file path is valid. If not, use the default path.
    if [[ -n "$new_log_path" ]]; then
        new_log_dir="$( dirname "$new_log_path" )"
        if [[ ! -d "$new_log_dir" ]]; then
            mkdir -p "$new_log_dir"
            if [[ $? -ne 0 ]]; then
                append_log "\n${RED}Could not create log directory: ${new_log_dir}. Using ${BTENFORCE_LOG_FILE}${NC}"
                new_log_path="$BTENFORCE_LOG_FILE"
            else
                append_log "\n${GREEN}Log directory confirmed: ${new_log_dir}${NC}"
            fi
        fi
    fi

    append_log "\n${GREEN}Writing configuration file: ${BTENFORCE_CONFIG}\n${NC}"
    cat << EOF > "$BTENFORCE_CONFIG"

## ╔══════════════════════════════╗
## ║ btenforce Configuration File ║
## ║  _     _____         _       ║
## ║ (_)   |_   _|__  ___| |___   ║
## ║ | |_____| |/ _ \/ __| '_  \  ║
## ║ | |_____| |  __/ (__| | | |  ║
## ║ |_|     |_|\___|\___|_| |_|  ║
## ║                              ║
## ║ ▶︎ https://i-techsupport.com  ║
## ║ ☎ (407) 265-2000 option: #1  ║
## ║ ✉ support@i-techsupport.com  ║
## ║ Author: Keith Myers, i-Tech  ║
## ║ (C) 2026 i-Tech Support Inc  ║
## ╚══════════════════════════════╝

# Version: ${VERSION}
# Configured on: $( date +"%Y-%m-%d %H:%M:%S" ) | via btenforce -configure option
# Configured by: ${loggedInUser}
# Configuration script path: ${SCRIPT_PATH}

# Enable/disable the daemon (true/false).
BTENFORCE_ACTIVE="$BTENFORCE_ACTIVE"

# Fully qualified domain name.
BTENFORCE_DOMAIN="$BTENFORCE_DOMAIN"

# Safari blocking option. 'enforce', 'allow'.
SAFARI_CONTROL="$SAFARI_CONTROL"

# Safari blocking method. 'osascript', 'pgrep'.
SAFARI_CONTROL_METHOD="$SAFARI_CONTROL_METHOD"

# Bluetooth blocking option. 'enforce', 'allow'.
BLUETOOTH_CONTROL="$BLUETOOTH_CONTROL"

# Login item control. 'enforce', 'allow'.
LOGIN_ITEM_CONTROL="$LOGIN_ITEM_CONTROL"

# School start time in 24-hour clock. Format: HH:MM.
BTENFORCE_START_TIME="$BTENFORCE_START_TIME"

# School stop time in 24-hour clock. Format: HH:MM.
BTENFORCE_STOP_TIME="$BTENFORCE_STOP_TIME"

# Log file path.
BTENFORCE_LOG_FILE="$new_log_path"

# Time constraint override.
TIME_CONSTRAINT_OVERRIDE="$TIME_CONSTRAINT_OVERRIDE"

# Log retention in days.
LOG_RETENTION="$LOG_RETENTION"
EOF

    chmod 644 "$BTENFORCE_CONFIG"
    chown root:wheel "$BTENFORCE_CONFIG"
    
    append_log "${GREEN}Configuration saved. Please review.\n${NC}"
    echo -e "${ORANGE}"
    cat "$BTENFORCE_CONFIG"
    echo -e "${NC}"

    # Prompt whether to start from the beginning or exit.
    if read -s -k 1 -t 120 "FINAL_RESTART?Would you like to restart the configuration? (Y/[${ORANGE}N${NC}]): "; then
        if [[ "$FINAL_RESTART" == "Y" || "$FINAL_RESTART" == "y" ]]; then
            append_log "\n${YELLOW}Restarting the configuration utility...${NC}"
            sleep 2
            configure_btenforce
        else
            append_log "\n${GREEN}Goodbye.${NC}"
            exit 0
        fi
    else
        append_log "\n${GREEN}Re-run the utility with btenforce -configure. Goodbye.${NC}"
        exit 1
    fi
}

# Function to add missing LOG_RETENTION to the config file if not found.
fix_missing_vars () {
    if grep "^LOG_RETENTION=" "$BTENFORCE_CONFIG" >/dev/null; then
        return 0
    else
        echo "LOG_RETENTION=\"180\"" >> "$BTENFORCE_CONFIG"
        return 0
    fi
}

# Run a command as the logged in user.
runAsUser() {
    # Recheck for logged in user before executing osascript in the event the user logs out between the initial check and this function call.
    loggedInUser=$( echo "show State:/Users/ConsoleUser" | scutil | awk '/Name :/ && ! /loginwindow/ { print $3 }' )

    if [[ -z "${loggedInUser}" ]] && [[ "${loggedInUser}" != "loginwindow" ]]; then
	    # Exit if no user is logged in. btenforce is user-facing.
	    append_log "No user logged in. Exiting."
	    exit 0
    fi

    # Execute the command sent to the function as the logged in user.
    launchctl asuser "$uid" sudo -u "$loggedInUser" "$@"
}

prune_logs () {
    local retention="${1:-$LOG_RETENTION}"
    local log_file="${2:-$BTENFORCE_LOG_FILE}"

    # Default to 180 days if missing or empty.
    if [[ -z "$retention" ]] || [[ "$retention" == "" ]]; then
        retention="180"
        if ! fix_missing_vars; then
            append_log "Failed to fix missing vars."
            return 1
        fi
    fi

    # Remove log files older than the retention period.
    find "$(dirname "$log_file")" \
        -name "$(basename "$log_file")" \
        -mtime +"${retention}" \
        -delete
    
    if [[ $? -ne 0 ]]; then
        return 1
    fi
}

# Install the LaunchDaemon if it doesn't exist.
install_daemon () {
    if [[ ! -f "$PLIST" ]]; then
        if [[ -f "$PLIST_SOURCE" ]]; then
            cp "$PLIST_SOURCE" "$PLIST"
            chown root:wheel "$PLIST"
            chmod 644 "$PLIST"
        else
            append_log "Error: LaunchDaemon source file not found: ${PLIST_SOURCE}"
            return 1
        fi

        daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )

        # Already running. Unload and reload.
        if [[ -n "$daemon_status" ]]; then
            launchctl bootout system/com.itech.btenforce
            sleep 1
            launchctl bootstrap system "$PLIST"
            sleep 1
            daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )
            if [[ -n "$daemon_status" ]]; then
                append_log "LaunchDaemon installed and reloaded."
                return 0
            else
                append_log "The daemon failed to reload."
                return 1
            fi
        else
            append_log "Installing new LaunchDaemon..."

            launchctl bootstrap system "$PLIST"

            sleep 1

            daemon_status=$( launchctl list | grep "com.itech.btenforce" || true )

            if [[ -n "$daemon_status" ]]; then
                append_log "LaunchDaemon installed and loaded."
                return 0
            else
                append_log "The daemon failed to start."
                return 1
            fi
        fi
    else
        append_log "LaunchDaemon already installed: ${PLIST}"
        return 0
    fi
}

# Check whether Bluetooth is on or off.
check_bluetooth () {
    btutil="/usr/local/bin/blueutil"

    # Source file if installed with the i-Tech package.
    btutil_source="/usr/local/share/blueutil"
        
    # Double check that blueutil is executable.
    if [[ ! -x "$btutil" ]]; then
        if [[ -f "$btutil_source" ]]; then
            cp "$btutil_source" "$btutil"
            if [[ ! -f "$btutil" ]]; then
                append_log "Could not find ${btutil}."
                return 1
            else
                chmod +x "$btutil"
                append_log "Copied Bluetooth utility from ${btutil_source} to ${btutil}. Version: $( /usr/local/bin/blueutil --version 2>/dev/null )"
            fi
        else
            append_log "Error: Could not find Bluetooth utility source file at ${btutil_source}. Exiting without action."
            return 1
        fi
    fi
    
    # Required to run as root.
    export BLUEUTIL_ALLOW_ROOT=1
    
    bstatus=$( runAsUser /usr/local/bin/blueutil -p )
    
    # If Bluetooth is off, turn it back on.
    if [[ "$bstatus" -eq 0 ]]; then
        runAsUser /usr/local/bin/blueutil --power 1
        append_log "Reactivated Bluetooth. User: ${loggedInUser}"
    fi
}

# Close Safari by killing the process if it's open.
check_safari () {
    
    if [[ "$SAFARI_CONTROL_METHOD" == "osascript" ]]; then
    
        safari_is_open=$( runAsUser osascript -e '
tell application "System Events"
set safariRunning to (name of processes) contains "Safari"
end tell

if safariRunning then
    tell application "Safari"
        if (count of windows) > 0 then
            return "true"
        end if
    end tell
end if

return "false"
' 2>/dev/null )
        if [[ "$safari_is_open" == "true" ]]; then
            killall Safari &> /dev/null
            append_log "Killed Safari for ${loggedInUser} via osascript."
            return 0
        fi
    elif [[ "$SAFARI_CONTROL_METHOD" == "pgrep" ]]; then
            safariProcs=$( ps aux | pgrep Safari )
            
        if pgrep -x "Safari" >/dev/null; then
            killall Safari &> /dev/null
            append_log "Killed Safari for ${loggedInUser} via pgrep"
            return 0
        fi
    else
        append_log "Invalid SAFARI_CONTROL_METHOD in ${BTENFORCE_CONFIG}."
        return 1
    fi
}

# Check whether the current date/time is during regular school hours.
during_school_hours () {
    
    if [[ "$BTENFORCE_DEBUG_MODE" == "true" || "$TIME_CONSTRAINT_OVERRIDE" == "true" ]]; then
        append_log "School hours are not considered due to debug mode or time constraint override set to true."
        return 0
    fi

    # Get current time
    current_hour=$(date +%H)
    current_minute=$(date +%M)
    day_of_week=$(date +%u)
    
    # Convert to integers
    current_total_minutes=$((10#$current_hour * 60 + 10#$current_minute))
    
    # Extract hours and minutes from HH:MM strings and calculate total minutes
    start_hour=${BTENFORCE_START_TIME%:*}
    start_minute=${BTENFORCE_START_TIME#*:}
    start_total_minutes=$((10#$start_hour * 60 + 10#$start_minute))

    end_hour=${BTENFORCE_STOP_TIME%:*}
    end_minute=${BTENFORCE_STOP_TIME#*:}
    end_total_minutes=$((10#$end_hour * 60 + 10#$end_minute))
    
    # Check if weekday (Mon–Fri) and time is between start and end
    if (( day_of_week >= 1 && day_of_week <= 5 )); then
        if (( current_total_minutes >= start_total_minutes && current_total_minutes < end_total_minutes )); then
            rm -f "$NW_FLAG" 2>/dev/null
            return 0
        fi
    fi

    # Create flag file so it doesn't log every minute when school is not in session.
    if [[ ! -f "$NW_FLAG" ]]; then
        append_log "Not during school hours. Creating flag file."
        touch "$NW_FLAG"
    fi
    
    return 1
}

check_login_items () {
    # Check if any login items exist for the current user.
    login_item_count=$(runAsUser osascript -e '
    tell application "System Events"
    count login items
    end tell
    ')
        
    if [[ "$login_item_count" -gt 0 ]]; then
        runAsUser osascript -e 'tell application "System Events" to delete login items'
        login_item_status="Removed ${login_item_count} login items for ${loggedInUser}"
        append_log "$login_item_status"
    fi
}

finished() {
    if [[ "$EXIT_CODE" -ne 0 ]]; then
        append_log "Exit code ${EXIT_CODE}."
    fi
    
    exit "$EXIT_CODE"
}

trapint() {
    if [[ -t 1 ]]; then
        append_log "Control-C was pressed. Script terminated by ${loggedInUser}."
    else
        append_log "btenforce received a Control-C sequence or SIGKILL from an unknown source."
    fi

	exit "$EXIT_CODE"
}

            

# ══════════╣ MAIN SCRIPT ╠═══════════

# Exit if running as a regular user. Prevents reconfiguring by standard users.
(( EUID != 0 )) && { append_log "Must be run as root"; exit 112; }

trap "finished" EXIT
trap "trapint" INT TERM
trap 'append_log "Error on line $LINENO: $(sed -n ${LINENO}p \"$0\")"' ERR

# Process arguments if there are any.
if [[ "$#" -ge 1 ]]; then
    while [[ "$#" -gt 0 ]]; do
        case $1 in
            -configure)
                configure_btenforce
                shift
            ;;
            -debug)
                BTENFORCE_DEBUG_MODE="true"
                append_log "----- [ Debug Mode ]-----"
                shift
            ;;
            *)
                append_log "Unknown option: $1"
                shift
            ;;
        esac
    done
fi

if ! prune_logs; then
    append_log "Failed to prune logs."
fi

# Source the configuration file.
if [[ -f "$BTENFORCE_CONFIG" ]]; then
    source "$BTENFORCE_CONFIG"
else
    append_log "Unable to find ${BTENFORCE_CONFIG}"
    exit 1
fi

if [[ "$BTENFORCE_DEBUG_MODE" == "true" ]]; then
    set -x
    append_log "Debug mode has been enabled. For support, please contact i-Tech at (407) 265-2000."
    append_log "support@i-techsupport.com  https://www.i-techsupport.com"
    debug_info
else
    set +x
fi

# Check if the daemon is active.
if [[ "$BTENFORCE_ACTIVE" == "true" ]]; then

    # Check the day and time, then perform actions if the current time is within the specified period.
    if during_school_hours; then
        
        # Install the daemon if missing, then check each item.
        if [[ ! -f "$PLIST" ]]; then
            append_log "Daemon not found. Reinstall btenforce."
            exit 113
        fi

        if [[ "$ACTIVE_USER" == "true" ]]; then

            if [[ "$LOGIN_ITEM_CONTROL" == "enforce" ]]; then
                check_login_items
            fi   
        
            if [[ "$BLUETOOTH_CONTROL" == "enforce" ]]; then
                check_bluetooth
            fi
            
            if [[ "$SAFARI_CONTROL" == "enforce" ]]; then
                check_safari
            fi
            
            if [[ "$LOGIN_ITEM_CONTROL" == "enforce" ]]; then
                check_login_items
            fi
        else
            append_log "No user logged in. Exiting."
            exit "$EXIT_CODE"
        fi
    fi
else
    append_log "BTENFORCE_ACTIVE is not set to true. Exiting."
fi

exit 0
